# Generated by Django 4.1.7 on 2023-03-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='file_path',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='some image', upload_to='productImages/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariant', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariantprice', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantprice',
            unique_together={('product', 'product_variant_one', 'product_variant_two', 'product_variant_three')},
        ),
    ]
