# Generated by Django 4.1.7 on 2023-03-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productimage_file_path_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='file_path',
            field=models.URLField(default='some'),
            preserve_default=False,
        ),
    ]
